image: ubuntu:14.04

stages:
    - build

before_script:
    - apt-get update && apt-get install -y git wget curl

build_job:
    stage: build
    script:
        - ./scripts/installUbuntuDeps.sh --cleanup
        - ./scripts/installErizo.sh
        - ./scripts/installNuve.sh
    artifacts:
        paths:
            - .
